server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/palate_poet
    username: postgres
    password: 2002

security:
  jwt:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7MhIwVTpHJVTpFtbshrkmV8m4MgpD+CEDbm9i4KAw61C64MCFtsoNT+KBC73Ki3jU8vQMUwdoCSlRODhpBOyfzSXlVweiHB+eKop/Tani72ihZbaj12c9bFJGBlmxCl+WIRYXiv4C7+F0aoHH5sBMnkzVgytxJLfh1TK1AsKTbziDGXDJv74szGJaZHZL6tsNKcISdebId7lvvf/dBiDo50YutgU73kMiLyc+sf3Y3WfepMMNppZR0tAe1+IfxOijzydD3FkkaN1s7Xb8nydQ0KJvJVvS7Ld6I+3szOGtICfOCAGeNaR7Wea7bw89tkITCGuvCFhzASZsoN+RgahHQIDAQAB
    private-key: MIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQDsyEjBVOkclVOkW1uyGuSZXybgyCkP4IQNub2LgoDDrULrgwIW2yg1P4oELvcqLeNTy9AxTB2gJKVE4OGkE7J/NJeVXB6IcH54qin9NqeLvaKFltqPXZz1sUkYGWbEKX5YhFheK/gLv4XRqgcfmwEyeTNWDK3Ekt+HVMrUCwpNvOIMZcMm/vizMYlpkdkvq2w0pwhJ15sh3uW+9/90GIOjnRi62BTveQyIvJz6x/djdZ96kww2mllHS0B7X4h/E6KPPJ0PcWSRo3WztdvyfJ1DQom8lW9Lst3oj7ezM4a0gJ84IAZ41pHtZ5rtvDz22QhMIa68IWHMBJmyg35GBqEdAgMBAAECgf9X/854C6jgZFXWLUJ5OBe9esQcxkcOxBkrSdyVs6GVF6rr3FbqcNHuZfgJ3yFqi6Nepc5xFiHshx/AeYo+AsrmMqWRJhkOUwnSYNk6HagnIpxowINVVywi/y4rNGohodx3m5OFIxtV1LOeE9v/meUhJjNbx6Ooj3+oOdsnzqlzXpqq4TTdklQjMi6ElYn3alZOp/YXAUKi39LVza1YEBWpAQxl+R+5xfli2rgnYe6j2aF2r5xi2tgwBo5ozjpGPgp9VgBRps3l2zMCzuv1JG2nqTHr6/tuO/04BSpgV8Qdpkcbg3K/kKEfY/qrJOkUZdEN9EC38evH3GwlToX1zmkCgYEA/wI7n2w0CJU0b1JsnNlRq3y0Ou5CqeavVhVhhnutDapTtBpJSPEJoJGSDB4piAvUSUBXFSNaxxApm594BXm2r1sQcnoTpV+nZR2uYx1mSDSMfc2qbpQXTM6yQrK6leFftSHqGTRTBJyYvWLsvXlpyCEvdPNwJGjrnDungB30f5cCgYEA7bPp5unmeb2iTA+0EuE8fdAuz/aUYm/eXz4x7EX/EHkMSo8z1H3xYe0/zrnAB39sVP+5dVfz/uHDY+F3GFTRuR0/mjb5F0dFOIjwlw9XaHAaxlR3LYK/uQLG5bZ0trOk2jZKudMVwUeHevsabr5VxqN9svohS/aE1wH3Z+muu2sCgYBAGfWW24Iw7iCiIxv+SXqIGu7LKX1EbCKDBxjez1Pu7XPhAAKP/VcoL6+AsExMUHzqdOvu+lYlV+C9p9ZpufC8H64AuMMbfPH9LvrZG1jMqbjvHrXK2hsJSaPxtC/G4UJHq+DGuSptLFgQsz9DWbPHhOADC/aSkHU5bp1qTR1avQKBgCxDkI77h3usIIjhc7sATm9vUQhQ9pjOFC7QOiOxdSnwIKXRvOkY+tYtg/BPDr9Wrym05ShA1KLmD6iN18ukH9nE5I8nJYN8NhutBIBczv4XwiSknfzPmDwvlDI6o8lR8qTf71JjSG3RkB0KnYV51CdFUqb9hS3MHjibmSK0lWE5AoGAFXG/LZ/OjQ+9dQ9LK6ilcmO9+MGQRnWLXOH29gHCHtFjN7B1/0/M1ki+r6hFwdK5HTE+iHbwIe5Dod59IZlidhrLNJ1r49NbEfeqxjIcbA2b/iOYPnqxSogBuh7Xxzk5NfZqjrO10NYjqTQ6a7hy8P9nTyVdLf9Lo7XGMVK4OG0=
    access-token-validity-time: 1800000
    refresh-token-validity-time: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
