import {
  cook,
  bookmark,
  shoppingBasket,
  door,
  kitchen,
  settings,
  logo,
  HeroImage,
} from "../../public";

import { Meal } from "@/types/types";

export const ImageIcons = {
  cook,
  bookmark,
  shoppingBasket,
  door,
  kitchen,
  settings,
  logo,
  hero: HeroImage,
};

export const mealData: Meal[] = [
  {
    mealName: "Spaghetti Bolognese",
    ingredients: [
      { name: "Spaghetti", inList: true },
      { name: "Ground beef", inList: true },
      { name: "Tomato sauce", inList: true },
      { name: "Onion", inList: true },
      { name: "Garlic", inList: false },
    ],
  },
  {
    mealName: "Chicken Caesar Salad",
    ingredients: [
      { name: "Chicken breast", inList: true },
      { name: "Romaine lettuce", inList: true },
      { name: "Parmesan cheese", inList: true },
      { name: "Croutons", inList: false },
      { name: "Caesar dressing", inList: true },
    ],
  },
];

export const ingredientsObj = {
  adzuki_beans: "🌱 Adzuki beans",
  agave_nectar: "🍯 Agave nectar",
  allspice: "🌶️ Allspice",
  almond_flour: "🌰 Almond flour",
  almonds: "🥜 Almonds",
  amaranth: "🌾 Amaranth",
  anchovies: "🐟 Anchovies",
  angel_hair_pasta: "🍝 Angel hair pasta",
  apricots: "🍑 Apricots",
  arrowroot: "🎯 Arrowroot",
  arroz_negro: "🍚 Arroz negro",
  arugula: "🌿 Arugula",
  avocado_oil: "🥑 Avocado oil",
  bacon: "🥓 Bacon",
  baking_powder: "🥄 Baking powder",
  baking_soda: "🥄 Baking soda",
  barley: "🌾 Barley",
  basmati_rice: "🍚 Basmati rice",
  bay_leaves: "🌿 Bay leaves",
  beets: "🍆 Beets",
  black_beans: "🖤 Black beans",
  blueberries: "🫐 Blueberries",
  bok_choy: "🥬 Bok choy",
  brown_rice: "🍚 Brown rice",
  bulgur: "🌾 Bulgur",
  butter_beans: "🧈 Butter beans",
  buttermilk: "🥛 Buttermilk",
  butternut_squash: "🎃 Butternut squash",
  cantaloupe: "🍈 Cantaloupe",
  capers: "🌿 Capers",
  capsicum: "🌶️ Capsicum",
  cardamom: "🌱 Cardamom",
  carrots: "🥕 Carrots",
  cashews: "🌰 Cashews",
  cauliflower: "🥦 Cauliflower",
  cayenne_pepper: "🌶️ Cayenne pepper",
  celeriac: "🌿 Celeriac",
  celery: "🌿 Celery",
  chai_tea: "☕ Chai tea",
  chamomile: "🌼 Chamomile",
  cherries: "🍒 Cherries",
  chia_seeds: "🌱 Chia seeds",
  chickpeas: "🌱 Chickpeas",
  chives: "🌿 Chives",
  cilantro: "🌿 Cilantro",
  cinnamon: "🌳 Cinnamon",
  citric_acid: "🍋 Citric acid",
  clams: "🐚 Clams",
  clarified_butter: "🧈 Clarified butter",
  cloves: "🌳 Cloves",
  cocoa_powder: "🍫 Cocoa powder",
  coconut_cream: "🥥 Coconut cream",
  coconut_milk: "🥥 Coconut milk",
  cod: "🐟 Cod",
  collard_greens: "🥬 Collard greens",
  cornmeal: "🌽 Cornmeal",
  cornstarch: "🌽 Cornstarch",
  corn_tortillas: "🌽 Corn tortillas",
  crab: "🦀 Crab",
  cranberries: "🍒 Cranberries",
  cranberry_sauce: "🍒 Cranberry sauce",
  crawfish: "🦞 Crawfish",
  cream: "🥛 Cream",
  cream_of_tartar: "🥄 Cream of tartar",
  crème_fraîche: "🥛 Crème fraîche",
  cumin: "🌱 Cumin",
  curry_powder: "🍛 Curry powder",
  dates: "🌴 Dates",
  dill: "🌿 Dill",
  eggplant: "🍆 Eggplant",
  fennel: "🌿 Fennel",
  fennel_seeds: "🌿 Fennel seeds",
  fenugreek: "🌱 Fenugreek",
  feta_cheese: "🧀 Feta cheese",
  figs: "🌰 Figs",
  fish_sauce: "🐟 Fish sauce",
  five_spice_powder: "🌶️ Five-spice powder",
  flaxseeds: "🌱 Flaxseeds",
  flour: "🌾 Flour",
  fusilli_pasta: "🍝 Fusilli pasta",
  galangal: "🌱 Galangal",
  garam_masala: "🌶️ Garam masala",
  garlic: "🧄 Garlic",
  ginger: "🌱 Ginger",
  gorgonzola_cheese: "🧀 Gorgonzola cheese",
  gouda_cheese: "🧀 Gouda cheese",
  graham_flour: "🌾 Graham flour",
  grapefruit: "🍊 Grapefruit",
  grapes: "🍇 Grapes",
  grapeseed_oil: "🥑 Grapeseed oil",
  greek_yogurt: "🥛 Greek yogurt",
  green_beans: "🌱 Green beans",
  green_onions: "🌿 Green onions",
  guavas: "🍈 Guavas",
  ham: "🍖 Ham",
  hazelnuts: "🌰 Hazelnuts",
  honey: "🍯 Honey",
  horseradish: "🌱 Horseradish",
  iceberg_lettuce: "🥬 Iceberg lettuce",
  jalapenos: "🌶️ Jalapeños",
  jasmine_rice: "🍚 Jasmine rice",
  juniper_berries: "🌿 Juniper berries",
  kaffir_lime_leaves: "🍃 Kaffir lime leaves",
  kale: "🥬 Kale",
  kidney_beans: "🍛 Kidney beans",
  kimchi: "🥬 Kimchi",
  kiwi: "🥝 Kiwi",
  lard: "🐖 Lard",
  lavender: "🌸 Lavender",
  lemon_balm: "🍋 Lemon balm",
  lemongrass: "🌿 Lemongrass",
  lentils: "🍲 Lentils",
  lime_juice: "🍈 Lime juice",
  lime_zest: "🍋 Lime zest",
  linguine_pasta: "🍝 Linguine pasta",
  lobster: "🦞 Lobster",
  loganberries: "🍇 Loganberries",
  macadamia_nuts: "🌰 Macadamia nuts",
  macaroni_pasta: "🍝 Macaroni pasta",
  mace: "🌿 Mace",
  mangoes: "🥭 Mangoes",
  maple_syrup: "🍁 Maple syrup",
  marjoram: "🌿 Marjoram",
  mascarpone_cheese: "🧀 Mascarpone cheese",
  matcha_powder: "🍵 Matcha powder",
  mayonnaise: "🥚 Mayonnaise",
  milk: "🥛 Milk",
  mint: "🌱 Mint",
  miso: "🍱 Miso",
  molasses: "🍯 Molasses",
  mozzarella_cheese: "🧀 Mozzarella cheese",
  mung_beans: "🌱 Mung beans",
  mushrooms: "🍄 Mushrooms",
  mussels: "🦪 Mussels",
  mustard: "🌿 Mustard",
  navy_beans: "🍛 Navy beans",
  nectarines: "🍑 Nectarines",
  nori: "🌿 Nori",
  nutmeg: "🌰 Nutmeg",
  oat_flour: "🌾 Oat flour",
  oats: "🌾 Oats",
  octopus: "🐙 Octopus",
  okra: "🌿 Okra",
  olives: "🫒 Olives",
  onions: "🧅 Onions",
  oranges: "🍊 Oranges",
  oregano: "🌿 Oregano",
  oysters: "🦪 Oysters",
  pancetta: "🥓 Pancetta",
  panko_bread_crumbs: "🍞 Panko bread crumbs",
  papaya: "🥭 Papaya",
  paprika: "🌶️ Paprika",
  parmesan_cheese: "🧀 Parmesan cheese",
  parsley: "🌿 Parsley",
  passion_fruit: "🍋 Passion fruit",
  peaches: "🍑 Peaches",
  peanut_butter: "🥜 Peanut butter",
  peanuts: "🥜 Peanuts",
  pears: "🍐 Pears",
  peas: "🌱 Peas",
  pecans: "🌰 Pecans",
  penne_pasta: "🍝 Penne pasta",
  peppers: "🌶️ Peppers",
  pineapple: "🍍 Pineapple",
  pine_nuts: "🌰 Pine nuts",
  pinto_beans: "🍛 Pinto beans",
  pistachios: "🌰 Pistachios",
  plums: "🍑 Plums",
  polenta: "🌽 Polenta",
  pomegranates: "🍎 Pomegranates",
  popeye: "🌿 Popeye",
  poppy_seeds: "🌱 Poppy seeds",
  potatoes: "🥔 Potatoes",
  pumpkin: "🎃 Pumpkin",
  pumpkin_seeds: "🎃 Pumpkin seeds",
  quinoa: "🌾 Quinoa",
  raisins: "🍇 Raisins",
  raspberries: "🍓 Raspberries",
  red_pepper_flakes: "🌶️ Red pepper flakes",
  rice: "🍚 Rice",
  rice_noodles: "🍜 Rice noodles",
  ricotta_cheese: "🧀 Ricotta cheese",
  rosemary: "🌿 Rosemary",
  rye_flour: "🌾 Rye flour",
  sage: "🌿 Sage",
  salmon: "🐟 Salmon",
  salt: "🧂 Salt",
  sauerkraut: "🥬 Sauerkraut",
  savory: "🌿 Savory",
  scallions: "🌱 Scallions",
  scallops: "🦪 Scallops",
  sea_salt: "🧂 Sea salt",
  sesame_oil: "🌱 Sesame oil",
  sesame_seeds: "🌱 Sesame seeds",
  shallots: "🧅 Shallots",
  shortening: "🌱 Shortening",
  shrimp: "🦐 Shrimp",
  sour_cream: "🥛 Sour cream",
  soy_sauce: "🌱 Soy sauce",
  spaghetti_pasta: "🍝 Spaghetti pasta",
  spinach: "🥬 Spinach",
  squash: "🎃 Squash",
  squid: "🦑 Squid",
  sriracha_sauce: "🌶️ Sriracha sauce",
  star_anise: "⭐ Star anise",
  strawberries: "🍓 Strawberries",
  sugar: "🍚 Sugar",
  sun_dried_tomatoes: "🍅 Sun-dried tomatoes",
  sunflower_seeds: "🌻 Sunflower seeds",
  sweet_potatoes: "🍠 Sweet potatoes",
  swiss_chard: "🌿 Swiss chard",
  tangerines: "🍊 Tangerines",
  tapioca: "🌾 Tapioca",
  tarragon: "🌿 Tarragon",
  tea: "🍵 Tea",
  thyme: "🌿 Thyme",
  tofu: "🌱 Tofu",
  tomatoes: "🍅 Tomatoes",
  truffles: "🍄 Truffles",
  turmeric: "🌿 Turmeric",
  vanilla_extract: "🌿 Vanilla extract",
  vegetable_oil: "🌱 Vegetable oil",
  vinegar: "🌿 Vinegar",
  walnuts: "🌰 Walnuts",
  wasabi: "🌱 Wasabi",
  watermelon: "🍉 Watermelon",
  white_wine: "🍷 White wine",
  whole_wheat_flour: "🌾 Whole wheat flour",
  wild_rice: "🌾 Wild rice",
  worcestershire_sauce: "🌿 Worcestershire sauce",
  yeast: "🌾 Yeast",
  yogurt: "🥛 Yogurt",
};

export const ingredients = Object.entries(ingredientsObj).map(
  ([value, label]) => ({ value, label }),
);

export const mealTimes = [
  { value: "breakfast", label: "Breakfast" },
  { value: "lunch", label: "Lunch" },
  { value: "dinner", label: "Dinner" },
  { value: "snack", label: "Snack" },
];

export const chefModes = [
  { value: "novice", label: "Novice" },
  { value: "intermediate", label: "Intermediate" },
  { value: "expert", label: "Expert" },
];

export const kitchenItems = [
  { id: "StoveTop", name: "Stove Top" },
  { id: "Oven", name: "Oven" },
  { id: "Blender", name: "Blender" },
  { id: "Toaster", name: "Toaster" },
  { id: "Microwave", name: "Microwave" },
  { id: "CoffeeMaker", name: "Coffee Maker" },
  { id: "Dishwasher", name: "Dishwasher" },
  { id: "Refrigerator", name: "Refrigerator" },
  { id: "CookwareSet", name: "Cookware Set" },
  { id: "CuttingBoard", name: "Cutting Board" },
  { id: "KnifeSet", name: "Knife Set" },
  { id: "UtensilHolder", name: "Utensil Holder" },
];
